apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-deployment
spec:
  selector: 
    matchLabels:
      app: web
  template:
    metadata:
      name: app-pod
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: gabrielcancio/kube-news:v1
        ports:
        - containerPort: 8080
        env: 
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "Pg#123"
        - name: DB_HOST
          value: postgres-service
